//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace office_library_backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.UserBookHistory = new HashSet<UserBookHistory>();
        }
    
        public int Id { get; set; }
        public int Author { get; set; }
        public string Title { get; set; }
        public Nullable<int> Genre { get; set; }
        public Nullable<System.DateTime> Year { get; set; }
    
        public virtual Author Author1 { get; set; }
        public virtual Genre_Dictionary Genre_Dictionary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserBookHistory> UserBookHistory { get; set; }
    }
}
