//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace office_library_backend.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class Entities2 : DbContext
    {
        public Entities2()
            : base("name=Entities2")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Book>()
                    .HasRequired<Genre_Dictionary>(b => b.Genre_Dictionary)
                    .WithMany(g => g.Book)
                    .HasForeignKey(b => b.Genre);

            modelBuilder.Entity<Book>()
                    .HasRequired<Author>(b => b.Author1)
                    .WithMany(a => a.Book)
                    .HasForeignKey(b => b.Author);

            modelBuilder.Entity<UserBookHistory>()
                    .HasKey(c => new {
                        c.BookId,
                        c.UserId
                    }); // Композитный ключ

            modelBuilder.Entity<UserBookHistory>()
                    .HasRequired<Book>(c => c.Book)
                    .WithMany(b => b.UserBookHistory)
                    .HasForeignKey(c => c.BookId)
                    .WillCascadeOnDelete(false);

            modelBuilder.Entity<UserBookHistory>()
                        .HasRequired<AspNetUsers>(c => c.AspNetUsers)
                        .WithMany(r => r.UserBookHistory)
                        .HasForeignKey(c => c.UserId)
                        .WillCascadeOnDelete(false);

            modelBuilder.Entity<AspNetUsers>()
                        .HasMany<AspNetRoles>(u => u.AspNetRoles)
                        .WithMany(r => r.AspNetUsers);

            modelBuilder.Entity<AspNetRoles>()
                        .HasMany<AspNetUsers>(r => r.AspNetUsers)
                        .WithMany(u => u.AspNetRoles);

            throw new UnintentionalCodeFirstException();
        }


        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Author> Author { get; set; }
        public virtual DbSet<Book> Book { get; set; }
        public virtual DbSet<Genre_Dictionary> Genre_Dictionary { get; set; }
        public virtual DbSet<UserBookHistory> UserBookHistory { get; set; }
    }
}
