//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace office_library_backend.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OfficeLibraryDataEntities : DbContext
    {
        public OfficeLibraryDataEntities()
            : base("name=OfficeLibraryDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Author> Author { get; set; }
        public virtual DbSet<Book> Book { get; set; }
        public virtual DbSet<Genre_Dictionary> Genre_Dictionary { get; set; }
        public virtual DbSet<MyRole_Dictionary> MyRole_Dictionary { get; set; }
        public virtual DbSet<MyUser> MyUser { get; set; }
        public virtual DbSet<UserBookHistory> UserBookHistory { get; set; }
    }
}
