//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace office_library_backend.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities1 : DbContext
    {
        public Entities1()
            : base("name=Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Book>()
                .HasOptional<Genre_Dictionary>(b => b.Genre_Dictionary)
                .WithMany(g => g.Book)
                .HasForeignKey(b => b.Genre);

            modelBuilder.Entity<Book>()
                .HasOptional<Author>(b => b.Author1)
                .WithMany(a => a.Book)
                .HasForeignKey(b => b.Author);

                //.HasOne(o => o.Customer)
                //.WithMany(c => c.Orders)
                //.HasForeignKey(o => o.CustomerId);

            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Author> Author { get; set; }
        public virtual DbSet<Book> Book { get; set; }
        public virtual DbSet<Genre_Dictionary> Genre_Dictionary { get; set; }
        public virtual DbSet<UserBookHistory> UserBookHistory { get; set; }
    }
}
