//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace office_library_backend.Models
{
    using office_library_backend.Models.MyDto;
    using System;
    using System.Collections.Generic;
    
    public partial class UserBookHistory 
    {
        public string UserId { get; set; }
        public string BookId { get; set; }
        public Nullable<System.DateTime> DateTaken { get; set; }
        public Nullable<System.DateTime> DateReturned { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Book Book { get; set; }
    }
}
